export const FETCH_USER_LIST_PAGE_REQUEST = "FETCH_USER_LIST_PAGE_REQUEST";
export const FETCH_USER_LIST_PAGE_SUCCESS = "FETCH_USER_LIST_PAGE_SUCCESS";
export const FETCH_USER_LIST_PAGE_FAILURE = "FETCH_USER_LIST_PAGE_FAILURE";

export const FETCH_USER_INFO_REQUEST = "FETCH_USER_INFO_REQUEST";
export const FETCH_USER_INFO_SUCCESS = "FETCH_USER_INFO_SUCCESS";
export const FETCH_USER_INFO_FAILURE = "FETCH_USER_INFO_FAILURE";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const HIDE_UPDATE_MODAL = "HIDE_UPDATE_MODAL";
export const SHOW_UPDATE_MODAL = "SHOW_UPDATE_MODAL";
export const HIDE_CREATE_MODAL = "HIDE_CREATE_MODAL";
export const SHOW_CREATE_MODAL = "SHOW_CREATE_MODAL";

export const SHOW_USER_INFO = "SHOW_USER_INFO";
export const HIDE_USER_INFO = "HIDE_USER_INFO";
